# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'test_wave' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Kanna', '~> 5.2.2'
  # Pods for test_wave
  pod 'Telegraph'

end
